const dishes={principais:[['Corte da casa','Picanha na brasa, arroz de alho, farofa crocante e vinagrete fresco.','89','ASSINATURA BRASA'],['Costela lentamente assada','Costela macia, purê de mandioca e molho do próprio assado.','76','TEMPO É INGREDIENTE'],['Peixe na brasa','Filé de peixe grelhado, arroz de coco e legumes da estação.','72','LEVE & CHEIO DE SABOR'],['Risoto de cogumelos','Arroz arbóreo, mix de cogumelos, parmesão e azeite de ervas.','64','VEGETARIANO']],entradas:[['Dadinho de tapioca','Crocante por fora, macio por dentro. Acompanha geleia de pimenta.','32','PARA COMPARTILHAR'],['Pão de alho da casa','Pão artesanal tostado na brasa com manteiga de alho e ervas.','24','DIRETO DO FOGO'],['Queijo coalho na brasa','Queijo dourado, melado de cana e um toque de limão.','29','UM CLÁSSICO BRASILEIRO'],['Salada da horta','Folhas frescas, tomate, cebola roxa e vinagrete cítrico.','28','FRESCOR À MESA']],sobremesas:[['Pudim da casa','Pudim cremoso de leite com calda de caramelo.','22','RECEITA DE AFETO'],['Banana na brasa','Banana assada, canela e sorvete de creme.','26','DOCE ENCONTRO'],['Brownie de chocolate','Brownie morno com sorvete e calda de chocolate.','28','PARA TERMINAR BEM']],bebidas:[['Caipirinha brasileira','Cachaça, limão fresco e açúcar.','26','UM BRINDE À CASA'],['Brasa tropical','Abacaxi, limão, hortelã e água com gás. Sem álcool.','22','FRESCO & TROPICAL'],['Suco natural','Consulte os sabores preparados com frutas da estação.','14','FEITO NA HORA'],['Água mineral','Com ou sem gás, 500 ml.','7','SIMPLES ASSIM']]};
const dishPhotos=[['steak.webp','Carne grelhada com batatas'],['ribs.webp','Costela assada'],['fish.webp','Filé de peixe preparado com acompanhamentos'],['risotto.webp','Risoto de cogumelos']];
function renderMenu(category){
 const grid=document.getElementById('menu-items');
 grid.classList.toggle('with-photos',category==='principais');
 grid.innerHTML=dishes[category].map(([name,description,price,tag],index)=>{
  const photo=category==='principais'?dishPhotos[index]:null;
  return `<article class="dish ${photo?'dish-card':''}">${photo?`<div class="dish-photo"><img src="${photo[0]}" alt="${photo[1]}" width="800" height="560" loading="lazy" decoding="async"><span>Imagem ilustrativa</span></div>`:''}<div class="dish-body"><span class="dish-tag">${tag}</span><div class="dish-top"><h3>${name}</h3><span class="price">R$ ${price}</span></div><p>${description}</p></div></article>`;
 }).join('');
}
renderMenu('principais');document.querySelectorAll('[data-category]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-category]').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-pressed','false')});button.classList.add('active');button.setAttribute('aria-pressed','true');renderMenu(button.dataset.category)}));
const booking=document.getElementById('booking'),order=document.getElementById('order-dialog');document.querySelectorAll('.reserve').forEach(button=>button.addEventListener('click',()=>booking.showModal()));document.querySelectorAll('.order').forEach(button=>button.addEventListener('click',()=>order.showModal()));document.querySelectorAll('dialog .close').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close()}}));document.getElementById('back-menu').addEventListener('click',()=>{order.close();document.getElementById('cardapio').scrollIntoView({behavior:'smooth'})});
const dateField=document.querySelector('[name=date]'),now=new Date();dateField.min=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');document.getElementById('year').textContent=now.getFullYear();
document.getElementById('booking-form').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.target);const date=String(data.get('date'));const day=new Date(date+'T12:00:00').getDay();const hour=Number(String(data.get('time')).split(':')[0]);if(day===1||(day>=2&&day<=5&&hour<18)||(day===0&&hour>=16)){dateField.setCustomValidity('Escolha uma data e horário dentro do funcionamento da casa.');dateField.reportValidity();return}dateField.setCustomValidity('');document.getElementById('message').value=`Olá, BRASA! Meu nome é ${data.get('name')}. Gostaria de consultar uma reserva para ${data.get('guests')}, no dia ${date.split('-').reverse().join('/')}, às ${data.get('time')}. Vocês têm disponibilidade?`;document.getElementById('booking-result').hidden=false;document.getElementById('booking-result').scrollIntoView({block:'nearest'});});document.querySelectorAll('#booking-form input,#booking-form select').forEach(field=>field.addEventListener('input',()=>{dateField.setCustomValidity('');document.getElementById('booking-result').hidden=true}));document.getElementById('copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(document.getElementById('message').value);document.getElementById('copy-status').textContent='Mensagem copiada. Nenhuma reserva foi enviada.'}catch{document.getElementById('message').select();document.getElementById('copy-status').textContent='Selecione e copie a mensagem acima.'}});

// Progressive enhancement: content remains visible without motion support.
const motionPreference=window.matchMedia('(prefers-reduced-motion: reduce)');
if(!motionPreference.matches && 'IntersectionObserver' in window){
 const targets=document.querySelectorAll('.story>div,.story-photo,.section-heading,.menu-photos figure,.occasion>.eyebrow,.occasion>h2,.occasions article,.visit>div,.faq>h2,.faq details');
 const revealObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.remove('reveal-pending');entry.target.classList.add('reveal-visible');revealObserver.unobserve(entry.target)}})},{threshold:0.08,rootMargin:'0px 0px -25px 0px'});
 targets.forEach((el,index)=>{if(el.getBoundingClientRect().top>window.innerHeight){el.classList.add('reveal-ready','reveal-pending');el.style.setProperty('--reveal-delay',`${(index%3)*65}ms`);revealObserver.observe(el)}});
 motionPreference.addEventListener('change',event=>{if(event.matches){targets.forEach(el=>el.classList.remove('reveal-pending'));revealObserver.disconnect()}});
}
